apiVersion: v1
kind: Pod
metadata:
  name: multi
  namespace: default
  app: webapp
spec:
  volumes:
    name: html
    emptyDir: { }
  containers:
  - name: backend
    image: nginx:latest
    volumeMounts:
      - name: html
        mountPath: /html
        command: [ "/bin/sh", "-c" ]
        args:
        - while true; do date >> /html/index.html; sleep 1; done;
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: debian
    image: nginx:latest
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"