apiVersion: v1
kind: Pod
metadata:
  name: control-sched-run
spec:
  containers:
  - image: nginx
    name: control-sched-run
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
    operator: Equal